import { EvmBatchProcessor} from '@subsquid/evm-processor'

// generated by the evm-typegen tool
// the events object contains typings for all events defined in the ABI
import { events } from './abi/Gravity'

// the registry of Subsquid-maintained public archives
import { lookupArchive } from '@subsquid/archive-registry'

export const CONTRACT = '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e'.toLowerCase()

export const processor = new EvmBatchProcessor()
  .setDataSource({
    // change the alias to run against other EVM networks, e.g.
    // lookupArchive('polygon')
    // lookupArchive('binance')
    archive: lookupArchive('eth-mainnet'),
    chain: 'https://rpc.ankr.com/eth'
  })
  .setBlockRange({ from: 9380380 })
  .setFinalityConfirmation(75)
  .addLog({
    address: [ CONTRACT ],
    topic0: [
      events.NewGravatar.topic,
      events.UpdatedGravatar.topic,
    ],
  })